#include <sciter-x.h>
#include <string.h>
#ifdef WINDOWS
#include <tlhelp32.h> /* CreateToolhelp32Snapshot / MODULEENTRY32W for DLL list diag */
#endif

typedef ISciterAPI *(SCAPI *SciterAPI_ptr)();

const char *SCITER_DLL_PATH = SCITER_DLL_NAME;

// getting ISciterAPI reference:

#if defined(STATIC_LIB) || defined(SCITER_BUILD)

EXTERN_C ISciterAPI *SCAPI SciterAPI();

ISciterAPI *_SAPI(ISciterAPI *ext) {
  static ISciterAPI *_api = NULL;
  if (ext)
    _api = ext;
  if (!_api) {
    _api = SciterAPI();
#if defined(__cplusplus) && !defined(PLAIN_API_ONLY)
//          tiscript::ni(_api->TIScriptAPI());
#endif
  }
  assert(_api);
  return _api;
}

#elif defined(WINDOWS)

/* --- XP FIX: try PE Import Table (static import) FIRST, fallback to
 * LoadLibrary + GetProcAddress SECOND.
 *
 * When libsciter.a (the tiny dlltool import library, auto-generated by our
 * build.bat before every go build) was linked in via `#cgo windows
 * LDFLAGS: -lsciter`, `SciterAPI` is resolved directly to a DLL import thunk
 * and sciter.dll appears in the PE Import Table.  The Windows loader
 * therefore loads sciter.dll (DLL_PROCESS_ATTACH etc.) in a SINGLE-THREADED
 * environment BEFORE Go's runtime spawns sysmon/GC worker threads.  This
 * eliminates the multi-threaded DllMain/TLS race that previously caused
 * SciterExec(SCITER_APP_INIT) to crash with NULL+0x02 on Windows XP even
 * though every SciterSetOption call succeeded and no Vista+ GFX DLLs were
 * present. */
extern __declspec(dllimport) ISciterAPI *SCAPI SciterAPI(void);

/* ===== MERGED FROM _xp_sciter_imports.c (single-file integration) =========
 * __attribute__((used)): Tells GCC/ld "DO NOT garbage-collect this function
 * even though nobody appears to call it".  The function takes the ADDRESS of
 * SciterAPI().  Taking the address FORCES the linker to actually resolve the
 * SciterAPI symbol from the libsciter.a import library.  Resolving that
 * symbol, in turn, FORCES sciter.dll to appear in the final EXE's PE Import
 * Table — which is the entire objective.  Without this, --gc-sections and
 * similar dead-code-stripping passes would sometimes drop the unused import
 * library entry completely and we'd silently fall back to the unsafe
 * LoadLibrary path (XP crash).
 * ======================================================================== */
__attribute__((used)) void *_xp_force_pe_import_table_sciter_dll_entry(void) {
  return (void *)(&SciterAPI);
}

static int _xp_static_import_works(void) {
  /* The linker will resolve &SciterAPI to a non-NULL import thunk address
   * IFF sciter.dll was actually added to the Import Table.  If the import
   * library was dropped for any reason we must not dereference it. */
  return (&SciterAPI != NULL);
}

static void _xp_show_sapi_diag(HMODULE hm, ISciterAPI *api,
                               int usedStaticImport) {
  TCHAR szPath[MAX_PATH];
  DWORD dwLen = GetModuleFileName(hm, szPath, MAX_PATH);
  TCHAR szMsg[1024];
  unsigned int v = api ? api->version : 0;
  UINT dllv = api ? api->SciterVersion(1) : 0;
  if (dwLen > 0) {
    wsprintf(
        szMsg,
        TEXT("_SAPI() diagnostic:\r\n") TEXT(
            "PE Import Table  : %s (static load = sciter.dll loaded BEFORE Go "
            "threads spawned)\r\n") TEXT("Loaded DLL path  : %s\r\n")
            TEXT("ISciterAPI*      : %p\r\n") TEXT(
                "ISciterAPI->vers : %u (expect %u for Sciter v6 API10)\r\n")
                TEXT("SciterVersion(1) : 0x%08X\r\n")
                    TEXT("click OK to continue."),
        usedStaticImport ? TEXT("YES ✅") : TEXT("NO (LoadLibrary fallback)"),
        szPath, api, v, (unsigned)SCITER_API_VERSION, dllv);
  } else {
    wsprintf(szMsg,
             TEXT("_SAPI() diagnostic:\r\n") TEXT("PE Import Table  : %s\r\n")
                 TEXT("GetModuleFileName FAILED (LastError=%lu)\r\n")
                     TEXT("ISciterAPI*      : %p\r\n")
                         TEXT("ISciterAPI->vers : %u (expect %u)\r\n")
                             TEXT("SciterVersion(1) : 0x%08X"),
             usedStaticImport ? TEXT("YES ✅")
                              : TEXT("NO (LoadLibrary fallback)"),
             (unsigned long)GetLastError(), api, v,
             (unsigned)SCITER_API_VERSION, dllv);
  }
  MessageBox(NULL, szMsg, TEXT("GoSciterXP _SAPI() Diagnostic"),
             MB_OK | MB_ICONINFORMATION);
}

ISciterAPI *_SAPI(ISciterAPI *ext) {
  static ISciterAPI *_api = NULL;
  if (ext)
    _api = ext;
  if (!_api) {
    int usedStatic = 0;
    HMODULE hm = NULL;
    /* ---- PATH A: PE Import Table (static import) — the XP fix! ---- */
    if (_xp_static_import_works()) {
      ISciterAPI *candidate = SciterAPI();
      if (candidate != NULL) {
        hm = GetModuleHandle(TEXT(SCITER_DLL_NAME));
        if (hm != NULL) {
          _api = candidate;
          usedStatic = 1;
#if XPBOOTSTRAP_VERBOSE
          _xp_show_sapi_diag(hm, _api, 1);
#endif
        }
      }
    }

    /* ---- PATH B: legacy LoadLibrary fallback (if static import broke) ---- */
    if (!_api) {
      hm = LoadLibrary(TEXT(SCITER_DLL_NAME));
      if (hm) {
        SciterAPI_ptr sciterAPI =
            (SciterAPI_ptr)GetProcAddress(hm, "SciterAPI");
        if (sciterAPI) {
          _api = sciterAPI();
#if XPBOOTSTRAP_VERBOSE
          _xp_show_sapi_diag(hm, _api, 0);
#endif
        } else {
          FreeLibrary(hm);
          { /* ---- Local scope for TCHAR szMsg[] (avoids VLAs / stack warnings
             * in case someone later changes size; braces keep stack frame
             * clean). Closing brace of this block is the one below (LINE 148) —
             * this accounts for the `{` visually appearing to be an unclosed
             * error handling block when snippet viewing starts at the TCHAR
             * line. */
            TCHAR szMsg[256];
            wsprintf(
                szMsg,
                TEXT("GetProcAddress(SciterAPI) FAILED on %s\r\nLastError=%lu"),
                TEXT(SCITER_DLL_NAME), (unsigned long)GetLastError());
            MessageBox(NULL, szMsg, TEXT("GoSciterXP ERROR"),
                       MB_OK | MB_ICONSTOP);
          } /* closes local scope opened at line 140 (above TCHAR declaration)
             */
          exit(-1); /* Hard stop — Sciter DLL loaded but missing the
                     * SciterAPI export (impossible with official DLL,
                     * but a corrupted/rogue DLL would cause an
                     * immediate NULL deref; hard exit keeps failure
                     * atomic and skips the later NDEBUG-disabled assert). */
        }
      } else {
        TCHAR szMsg[256];
        wsprintf(szMsg, TEXT("LoadLibrary(%s) FAILED\r\nLastError=%lu"),
                 TEXT(SCITER_DLL_NAME), (unsigned long)GetLastError());
        MessageBox(NULL, szMsg, TEXT("GoSciterXP ERROR"), MB_OK | MB_ICONSTOP);
        exit(-1); /* Hard stop — cannot proceed without Sciter DLL. This
                   * avoids relying on the later assert(_api) (which is a
                   * no-op in Release NDEBUG builds) and keeps the failure
                   * path atomic / self-explanatory at the error site. */
      }
    }
  }

  if (_api) {
    UINT v0 = _api->SciterVersion(0);
    UINT v1 = _api->SciterVersion(1);
    UINT v2 = _api->SciterVersion(2);
    UINT v3 = _api->SciterVersion(3);
    if (v0 != SCITER_VERSION_0 || v1 != SCITER_VERSION_1 ||
        v2 != SCITER_VERSION_2 || v3 != SCITER_VERSION_3) {
      TCHAR szMsg[512];
      wsprintf(szMsg,
               TEXT("Sciter DLL version mismatch!\r\n\r\n")
               TEXT("Header expects: %u.%u.%u.%u\r\n")
               TEXT("DLL reports   : %u.%u.%u.%u\r\n\r\n")
               TEXT("Please use sciter.dll version %u.%u.%u.%u"),
               (UINT)SCITER_VERSION_0, (UINT)SCITER_VERSION_1,
               (UINT)SCITER_VERSION_2, (UINT)SCITER_VERSION_3, v0, v1, v2, v3,
               (UINT)SCITER_VERSION_0, (UINT)SCITER_VERSION_1,
               (UINT)SCITER_VERSION_2, (UINT)SCITER_VERSION_3);
      MessageBox(NULL, szMsg, TEXT("GoSciterXP ERROR - Version Mismatch"),
                 MB_OK | MB_ICONSTOP);
      _api = NULL;
    }
  }

  assert(_api);
  if (!_api) {
    //::MessageBox(NULL, TEXT("Sciter engine not found,
    //: quiting"),TEXT("Error"),MB_OK);
    exit(-1);
  }
  return _api;
}

/* ===========================================================================
 * XPBootstrapAndCreateWindow()
 * 1:1 REPLICA OF c_xp_test.exe STEPS 4..12 — EXACT same C code that already
 * proved to work 100% on Windows XP (Sciter 6.0.4.5 DLL).  We do NOT trust
 * Go syscall.Syscall VTable slot invocation for the CRITICAL bootstrap — the
 * VTable slot offsets and __stdcall parameter layout are handled here by the
 * C compiler, which is exactly how c_xp_test.exe achieves success.
 *
 * Flow:
 *   1. Force SAPI() = LoadLibrary + Get ISciterAPI ptr (pure C steps 0..3)
 *   2. SciterVersion(TRUE)                 -> warm up DLL internals
 *   3. SetOption(GFX_LAYER = GDI)         -> FORCE GDI CPU RENDER (skip D2D/D3D
 * probes!)
 *   4. SetOption(DEBUG_MODE = 0)          -> disable inspector server
 *   5. SetOption(RT17 UIAutomation = 0)   -> disable Vista+ UIA
 *   6. SetOption(RT20 DirectComposition = 0) -> disable Vista+ DComp
 *   7. SetOption(UX_THEMING = 1)          -> "unisex" cross-platform theme
 *   8. SetOption(SCRIPT_FEATURES = basic) -> minimal script perms
 *   9. SciterExec(SCITER_APP_INIT=2)      -> THE CRITICAL INTERNAL INIT!
 *  10. Strip unsafe XP flags + default RECT -> 800x600 local stack RECT
 *  11. SciterCreateWindow(...)            -> returns HWINDOW or NULL
 *
 * Go side calls this via CGO as:
 *   HWINDOW C.XPBootstrapAndCreateWindow(UINT flags, RECT* frame, HWINDOW
 * parent)
 * ===========================================================================
 */
#if defined(WINDOWS)
/* Only compile for Windows target.  The caller in sciter_windows.go is already
 * guarded by file tag _windows.go so this symbol is only required/linked on
 * Windows. */
#include <windows.h>
#ifndef SCITER_APP_INIT
#define SCITER_APP_INIT 2
#endif
#ifndef GFX_LAYER_GDI
#define GFX_LAYER_GDI 1
#endif
#ifndef BAD_HWINDOW
#define BAD_HWINDOW 0
#endif
/* Forward declaration of SAPI() — defined at bottom of this translation unit
 * as:  ISciterAPI *SAPI(void) { return _SAPI(NULL); }   Without this forward
 * declaration the call at line 204 would fall through to implicit C int-return
 * and cause a pointer/truncation + conflict with the real SAPI() later. */
struct _ISciterAPI; /* forward opaque tag (not typedef'ed yet below) */
typedef struct _ISciterAPI ISciterAPI;
extern ISciterAPI *SAPI(void);
/* These SCITER_RT_OPTIONS enum values are HARDCODED here to a numeric literal
 * because they are the SAME across Sciter v6 and we want this file to be
 * self-contained.  They are verified against sciter-x-def.h at the top of
 * this session (C header and Go types.go are byte-for-byte identical so this
 * is safe). */
enum {
  XPOPT_SMOOTH_SCROLL = 1,
  XPOPT_CONNECTION_TIMEOUT = 2,
  XPOPT_HTTPS_ERROR = 3,
  XPOPT_FONT_SMOOTHING = 4,
  /* 5 intentionally unused */
  XPOPT_TRANSPARENT_WINDOW = 6,
  XPOPT_SET_GPU_BLACKLIST = 7,
  XPOPT_SET_SCRIPT_RUNTIME_FEATURES = 8,
  XPOPT_SET_GFX_LAYER = 9,
  XPOPT_SET_DEBUG_MODE = 10,
  XPOPT_SET_UX_THEMING = 11,
  XPOPT_ALPHA_WINDOW = 12,
  XPOPT_SET_INIT_SCRIPT = 13,
  XPOPT_SET_MAIN_WINDOW = 14,
  XPOPT_SET_MAX_HTTP_DATA_LENGTH = 15,
  XPOPT_SET_PX_AS_DIP = 16,
  XPOPT_ENABLE_UIAUTOMATION = 17, /* Vista+ only, OFF on XP */
  XPOPT_USE_INTERNAL_HTTP_CLIENT = 18,
  XPOPT_EXTENDED_TOUCHPAD_SUPPORT = 19,
  XPOPT_ENABLE_DIRECT_COMPOSITION = 20 /* Vista+ only, OFF on XP */
};
enum {
  XP_ALLOW_FILE_IO = 0x00000001,
  XP_ALLOW_SOCKET_IO = 0x00000002,
  XP_ALLOW_EVAL = 0x00000004,
  XP_ALLOW_SYSINFO = 0x00000008,
  XP_ALLOW_CMODULES = 0x00000010
};
enum {
  XP_SW_MAIN = 0x00000001,
  XP_SW_TITLEBAR = 0x00000002,
  XP_SW_RESIZEABLE = 0x00000004,
  XP_SW_UNSAFE_MASK = 0x008 | 0x020 | 0x040 | 0x100 | 0x200
};

/* ===========================================================================
 * XPBOOTSTRAP_VERBOSE — CRITICAL STACK SAVER!
 *   Go CGO runs the bootstrap on a TINY thread stack (~4 KB guard page).
 *   Each MessageBoxW internally calls DialogBoxIndirectParam → CreateWindowEx
 *   → USER32/GDI internal state + nested modal message loop, and each level
 *   costs 500–2000 bytes of additional stack.  When XPBOOTSTRAP_VERBOSE=1,
 *   we have ~12 NESTED MessageBox calls, which means USER32/GDI stack usage
 *   ALONE is ~6–24 KB — ENOUGH TO OVERFLOW THE CGO STACK COMPLETELY AND
 *   OVERWRITE THE SAVED RETURN ADDRESS BEFORE THE FINAL #13b RET RUNS.
 *   This was the ROOT CAUSE of "Exception 0xc0000005 PC=0x20fd2000" even
 *   after szMsg/szBig/szRet were moved to static storage.
 * Set = 1 ONLY for debugging.  Set = 0 for production + #13b transition test.
 * ===========================================================================
 */
#ifndef XPBOOTSTRAP_VERBOSE
#define XPBOOTSTRAP_VERBOSE                                                    \
  0 /* 0 = production (minimal nesting); 1 = verbose debug */
#endif

HWINDOW XPBootstrapAndCreateWindow(UINT creationFlags,
                                   const RECT *frame OPTIONAL, HWINDOW parent) {
  /* CRITICAL (XP CGO STACK FIX):
   *   Go runtime gives CGO calls a TINY initial stack (~4-8 KB).  Previously we
   *   declared szMsg[512] + szBig[4096] + szRet[512] as STACK-LOCAL arrays
   *   (~10 KB total), which, combined with nested MessageBoxW call frames,
   *   overflowed the CGO thread stack and overwrote the saved return address
   *   on the stack.  On function return EIP was popped to a string-data
   *   address (e.g. 0x20fd2000) which immediately caused
   *   Exception 0xc0000005 at PC=0x20fd2000 exactly when clicking OK in #13b.
   * Fix: All large buffers are `static` → live in .data / .bss segment, 0
   * stack bytes.  ZeroMemory on entry to avoid cross-call leakage of stale
   * contents (harmless but cleaner). */
  static TCHAR szMsg[512];
  SBOOL rOpt;
  UINT rExec;
  UINT rVersion;
  HWINDOW hwndRet = BAD_HWINDOW;
  ZeroMemory(szMsg, sizeof(szMsg));

  /* --- STEP 0..3: obtain ISciterAPI ptr via SAPI() (same LoadLibrary flow
   * that diagnostic MessageBox already lives inside, so this also fires the
   * diagnostic dialog on the very first call). --- */
  ISciterAPI *api = SAPI();
  if (!api) {
#if XPBOOTSTRAP_VERBOSE
    MessageBox(NULL, TEXT("XPBootstrap FAILED at SAPI() — api=NULL!\r\n"),
               TEXT("GoSciterXP Bootstrap #0"), MB_OK | MB_ICONSTOP);
#endif
    return BAD_HWINDOW;
  }

  /* --- STEP 4 (pure C STEP 76): SciterVersion(TRUE) warm up. --- */
  rVersion = api->SciterVersion(TRUE);
#if XPBOOTSTRAP_VERBOSE
  wsprintf(szMsg,
           TEXT("STEP 4: api->SciterVersion(TRUE) returned 0x%08X\r\nClick OK "
                "to continue (next: 6 x SetOption)."),
           rVersion);
  MessageBox(NULL, szMsg, TEXT("GoSciterXP Bootstrap #4"),
             MB_OK | MB_ICONINFORMATION);
#endif

  /* --- Always-on XP compatibility (6 x SciterSetOption calls): ---
   * Always executed by default on every Windows build.
   *   (a) guarantee XP SP3 compatibility (GFX layer = GDI is the #1 fix for the
   *       NULL+0x02 crash inside the Direct2D init path of Sciter DLL on XP;
   *   (b) removed the old -tags xp / CFLAGS XP_COMPAT build-tag infrastructure;
   *   (c) no visual/perf impact on modern systems (Sciter handles GDI
   * gracefully). ORDER MATTERS — GFX_LAYER must be set FIRST before any other
   * option.
   * ----------------------------------------------------------------------- */

  /* --- STEPS 5..10: six SetOption calls — ORDER MATTERS! GFX first! --- */
  /* STEP 5 -> GFX = GDI! THIS IS THE #1 THING that prevents NULL+0x02 crash. */
  rOpt =
      api->SciterSetOption(NULL, XPOPT_SET_GFX_LAYER, (UINT_PTR)GFX_LAYER_GDI);
#if XPBOOTSTRAP_VERBOSE
  wsprintf(szMsg,
           TEXT("STEP 5/10: SetOption(GFX_LAYER=GDI) returned %d (expect "
                "1).\r\nClick OK for next: DEBUG_MODE=0"),
           rOpt);
  MessageBox(NULL, szMsg, TEXT("GoSciterXP Bootstrap #5"),
             MB_OK | MB_ICONINFORMATION);
#endif

  rOpt = api->SciterSetOption(NULL, XPOPT_SET_DEBUG_MODE, (UINT_PTR)0);
#if XPBOOTSTRAP_VERBOSE
  wsprintf(szMsg,
           TEXT("STEP 6/10: SetOption(DEBUG_MODE=0) returned %d (expect "
                "1).\r\nNext: UIA=0"),
           rOpt);
  MessageBox(NULL, szMsg, TEXT("GoSciterXP Bootstrap #6"),
             MB_OK | MB_ICONINFORMATION);
#endif

  rOpt = api->SciterSetOption(NULL, XPOPT_ENABLE_UIAUTOMATION, (UINT_PTR)0);
#if XPBOOTSTRAP_VERBOSE
  wsprintf(szMsg,
           TEXT("STEP 7/10: SetOption(UIA17=0) returned %d (expect "
                "1).\r\nNext: DComp=0"),
           rOpt);
  MessageBox(NULL, szMsg, TEXT("GoSciterXP Bootstrap #7"),
             MB_OK | MB_ICONINFORMATION);
#endif

  rOpt =
      api->SciterSetOption(NULL, XPOPT_ENABLE_DIRECT_COMPOSITION, (UINT_PTR)0);
#if XPBOOTSTRAP_VERBOSE
  wsprintf(szMsg,
           TEXT("STEP 8/10: SetOption(DComp20=0) returned %d (expect 0 on "
                "XP).\r\nNext: UX_THEMING=1"),
           rOpt);
  MessageBox(NULL, szMsg, TEXT("GoSciterXP Bootstrap #8"),
             MB_OK | MB_ICONINFORMATION);
#endif

  rOpt = api->SciterSetOption(NULL, XPOPT_SET_UX_THEMING, (UINT_PTR)1);
#if XPBOOTSTRAP_VERBOSE
  wsprintf(szMsg,
           TEXT("STEP 9/10: SetOption(UX_THEMING=1) returned %d (expect "
                "1).\r\nNext: SCRIPT_FEATURES"),
           rOpt);
  MessageBox(NULL, szMsg, TEXT("GoSciterXP Bootstrap #9"),
             MB_OK | MB_ICONINFORMATION);
#endif

  rOpt = api->SciterSetOption(
      NULL, XPOPT_SET_SCRIPT_RUNTIME_FEATURES,
      (UINT_PTR)(XP_ALLOW_FILE_IO | XP_ALLOW_EVAL | XP_ALLOW_SYSINFO));
#if XPBOOTSTRAP_VERBOSE
  wsprintf(szMsg,
           TEXT("STEP 10/10: SetOption(SCRIPT=FILE|EVAL|SYSINFO) returned %d "
                "(expect 1).\r\n\r\nNEXT = STEP 10-B SUPER DIAGNOSTIC → Click "
                "OK to run (critical!)."),
           rOpt);
  MessageBox(NULL, szMsg, TEXT("GoSciterXP Bootstrap #10"),
             MB_OK | MB_ICONWARNING);
#endif

#if XPBOOTSTRAP_VERBOSE
  /* =======================================================================
   * STEP 10-B — SUPER DIAGNOSTIC BEFORE CALLING SciterExec(APP_INIT=2)!
   * Checks:
   *   (A) THREE consecutive SciterSetOption(GFX=GDI) calls, each retval saved.
   *       ISciterAPI has no SciterGetOption(), so triple-invocation is the
   *       best-effort way to confirm the option was really accepted.
   *   (B) LoadLibraryW d2d1 / d3d11 / dxgi / dwrite — are these accidentally
   *       present on C:\bin and partially exported?
   *   (C) List every DLL loaded in this process (Toolhelp32 MODULEENTRY32W)
   *       Compare list vs single-threaded c_xp_test.exe to find Go-specific
   *       DLLs that could affect Sciter's internal init branching.
   * Needs <tlhelp32.h> (included at top of file, WINDOWS only).
   * ======================================================================= */
  {
    /* CRITICAL (XP CGO STACK FIX #2):
     *   This 4096 × 2-byte (8 KB!) buffer was the main culprit.  Combined with
     *   szMsg[1 KB] above, several nested MessageBox call frames (USER32 + GDI
     *   internal state) and the CGO prologue, the function grew to ~12 KB of
     *   stack space and smashed past the 4-8 KB CGO guard page on the Go
     *   thread.  Moving it to static drops the stack frame by ~8 KB
     * immediately.
     */
    static TCHAR szBig[4096];
    int nLen = 0;
    UINT rSetA = 999, rSetB = 999, rSetC = 999;
    HMODULE hD2D1 = NULL, hD3D11 = NULL, hDXGI = NULL, hDWrite = NULL;
    UINT gleD2D1 = 0, gleD3D11 = 0, gleDXGI = 0, gleDWrite = 0;
    HANDLE hSnap = NULL;
    ZeroMemory(szBig, sizeof(szBig));

    /* (A) Triple-confirm GFX Layer = GDI */
    rSetA = (UINT)api->SciterSetOption(NULL, XPOPT_SET_GFX_LAYER,
                                       (UINT_PTR)GFX_LAYER_GDI);
    rSetB = (UINT)api->SciterSetOption(NULL, XPOPT_SET_GFX_LAYER,
                                       (UINT_PTR)GFX_LAYER_GDI);
    rSetC = (UINT)api->SciterSetOption(NULL, XPOPT_SET_GFX_LAYER,
                                       (UINT_PTR)GFX_LAYER_GDI);

    /* (B) Attempt LoadLibraryW for all Vista+ GFX DLLs */
    SetLastError(0);
    hD2D1 = LoadLibraryW(L"d2d1.dll");
    gleD2D1 = GetLastError();
    SetLastError(0);
    hD3D11 = LoadLibraryW(L"d3d11.dll");
    gleD3D11 = GetLastError();
    SetLastError(0);
    hDXGI = LoadLibraryW(L"dxgi.dll");
    gleDXGI = GetLastError();
    SetLastError(0);
    hDWrite = LoadLibraryW(L"dwrite.dll");
    gleDWrite = GetLastError();

    nLen = wsprintf(
        szBig,
        TEXT("GO XP SUPER DIAGNOSTIC — right before SciterExec(APP_INIT=2)\r\n")
            TEXT("============================================================="
                 "===\r\n") TEXT("(A) 3x "
                                 "SciterSetOption(SCITER_SET_GFX_LAYER=9, "
                                 "GFX_LAYER_GDI=1)\r\n")
                TEXT("    call 1 / 3 returned %u  (expect 1)\r\n") TEXT(
                    "    call 2 / 3 returned %u  (expect 1)\r\n")
                    TEXT("    call 3 / 3 returned %u  (expect 1)\r\n") TEXT(
                        "    → 3×1 = GDI mode accepted; any 0 = rejected!\r\n")
                        TEXT("-------------------------------------------------"
                             "---------------\r\n") TEXT("(B) LoadLibrary "
                                                         "Vista-GFX DLLs (XP "
                                                         "SHOULD ALL "
                                                         "FAIL gle=126 = "
                                                         "MOD_NOT_FOUND):\r\n")
                            TEXT("    d2d1.dll    h=%p   gle=%u\r\n") TEXT(
                                "    d3d11.dll   h=%p   gle=%u\r\n")
                                TEXT("    dxgi.dll    h=%p   gle=%u\r\n") TEXT(
                                    "    dwrite.dll  h=%p   gle=%u\r\n")
                                    TEXT("    → IF ANY h!=NULL, Sciter could "
                                         "load them → ROOT CAUSE "
                                         "CANDIDATE!\r\n")
                                        TEXT("---------------------------------"
                                             "-----"
                                             "--------------------------\r\n")
                                            TEXT("(C) ALL DLLs LOADED IN THIS "
                                                 "Go-PROCESS (compare vs "
                                                 "c_xp_test.exe!):\r\n"),
        rSetA, rSetB, rSetC, (void *)hD2D1, gleD2D1, (void *)hD3D11, gleD3D11,
        (void *)hDXGI, gleDXGI, (void *)hDWrite, gleDWrite);

    if (hD2D1)
      FreeLibrary(hD2D1);
    if (hD3D11)
      FreeLibrary(hD3D11);
    if (hDXGI)
      FreeLibrary(hDXGI);
    if (hDWrite)
      FreeLibrary(hDWrite);

    /* Toolhelp32 snapshot of loaded modules */
    hSnap = CreateToolhelp32Snapshot(TH32CS_SNAPMODULE, GetCurrentProcessId());
    if (hSnap != INVALID_HANDLE_VALUE) {
      MODULEENTRY32W me;
      BOOL b;
      ZeroMemory(&me, sizeof(me));
      me.dwSize = sizeof(MODULEENTRY32W);
      for (b = Module32FirstW(hSnap, &me); b; b = Module32NextW(hSnap, &me)) {
        if (nLen > (int)(sizeof(szBig) / sizeof(TCHAR)) - 128) {
          nLen += wsprintf(szBig + nLen, TEXT("  ... [list truncated]\r\n"));
          break;
        }
        nLen += wsprintf(szBig + nLen, TEXT("  * %s\r\n"), me.szModule);
      }
      CloseHandle(hSnap);
    } else {
      DWORD gle = GetLastError();
      nLen += wsprintf(
          szBig + nLen,
          TEXT("  [Toolhelp32 FAILED gle=%lu — can't list DLLs]\r\n"), gle);
    }

    MessageBox(NULL, szBig,
               TEXT("GoSciterXP #10b SUPER DIAG — write down (A) and (B)!"),
               MB_OK | MB_ICONWARNING | MB_TOPMOST);
  }
#endif /* XPBOOTSTRAP_VERBOSE */

  /* --- STEP 11 (pure C STEP 107): SCITER_APP_INIT = THE CRITICAL STEP ---
   * Because GFX_LAYER is already GDI at this point, the internal singletons
   * created by SciterExec are GDI-based and succeed on XP. */
  rExec = api->SciterExec((UINT)SCITER_APP_INIT, 0, 0);
#if XPBOOTSTRAP_VERBOSE
  wsprintf(szMsg,
           TEXT("STEP 11/13: SciterExec(APP_INIT=2) returned %u (pure-C got "
                "1).\r\nClick OK for next: CreateWindow"),
           rExec);
  MessageBox(NULL, szMsg, TEXT("GoSciterXP Bootstrap #11"),
             MB_OK | MB_ICONINFORMATION);
#endif

  /* --- STEP 12: sanitize window flags (remove XP-incompatible bits). --- */
  UINT safe = creationFlags & ~((UINT)XP_SW_UNSAFE_MASK);
  if ((safe & (XP_SW_MAIN | XP_SW_TITLEBAR)) == 0) {
    safe |= (XP_SW_MAIN | XP_SW_TITLEBAR);
  }

  /* Stack-local non-null RECT (so caller can pass NULL and still works). */
  RECT localRect;
  const RECT *prc = frame;
  if (prc == NULL) {
    localRect.left = 0;
    localRect.top = 0;
    localRect.right = 800;
    localRect.bottom = 600;
    prc = &localRect;
  }

#if XPBOOTSTRAP_VERBOSE
  wsprintf(szMsg,
           TEXT("STEP 12/13: safeFlags=0x%X, rect=(%d,%d)-(%d,%d).\r\nClick OK "
                "→ SciterCreateWindow (last step!)."),
           safe, prc->left, prc->top, prc->right, prc->bottom);
  MessageBox(NULL, szMsg, TEXT("GoSciterXP Bootstrap #12"),
             MB_OK | MB_ICONINFORMATION);
#endif

  /* --- STEP 13: SciterCreateWindow.
   * VTable signature expects LPRECT (non-const RECT*) so cast away const. ---
   */
  HWINDOW hwnd = api->SciterCreateWindow(safe, (LPRECT)prc, NULL, NULL, parent);
  if (hwnd == NULL) {
    MessageBox(NULL,
               TEXT("STEP 13 FAILED: SciterCreateWindow returned NULL!\r\n"),
               TEXT("GoSciterXP Bootstrap #13"), MB_OK | MB_ICONSTOP);
    return BAD_HWINDOW;
  }
#if XPBOOTSTRAP_VERBOSE
  wsprintf(szMsg,
           TEXT("STEP 13/13 SUCCESS: hwnd=%p.\r\nClick OK → C function will "
                "return hwnd to Go layer next."),
           hwnd);
  MessageBox(NULL, szMsg, TEXT("GoSciterXP Bootstrap #13"),
             MB_OK | MB_ICONINFORMATION);
#endif

  hwndRet = hwnd;
#if XPBOOTSTRAP_VERBOSE
  {
    /* CRITICAL (XP CGO STACK FIX #3): 1 KB stack → static, another -2 KB. */
    static TCHAR szRet[512];
    ZeroMemory(szRet, sizeof(szRet));
    wsprintf(szRet,
             TEXT("#13b: About to return hwnd=%p from "
                  "XPBootstrapAndCreateWindow → C→Go bridge.\r\nClick OK → RET "
                  "instruction will run and CGO bridge will copy return value "
                  "back to Go.\r\n(STACK FIX APPLIED: szMsg/szBig/szRet are "
                  "ALL static now — should NOT crash after OK anymore!)"),
             hwndRet);
    MessageBox(NULL, szRet, TEXT("GoSciterXP #13b (STACK FIXED!)"),
               MB_OK | MB_ICONWARNING | MB_TOPMOST);
  }
#endif
  return hwndRet;
}
#endif /* WINDOWS */

#elif defined(OSX)

// typedef ISciterAPI* SCAPI (*SciterAPI_ptr)();

ISciterAPI *_SAPI(ISciterAPI *ext) {
  static ISciterAPI *_api = NULL;
  if (ext)
    _api = ext;
  if (!_api) {
    pid_t pid;
    char pathbuf[PROC_PIDPATHINFO_MAXSIZE];
    char folderpath[PROC_PIDPATHINFO_MAXSIZE];
    pid = getpid();
    proc_pidpath(pid, pathbuf, sizeof(pathbuf));
    realpath(pathbuf, folderpath);
    *strrchr(folderpath, '/') = '\0';

    void *lib_sciter_handle = dlopen(SCITER_DLL_NAME, RTLD_LOCAL | RTLD_LAZY);
    if (!lib_sciter_handle) {
      const char *lookup_paths[] = {
          "/" SCITER_DLL_NAME,
          "/../Frameworks/" SCITER_DLL_NAME, // - (bundle
                                             // folder)/Contents/Frameworks/
          "/../../../" SCITER_DLL_NAME // aside of bundle folder (SDK samples)
      };
      for (int n = 0; !lib_sciter_handle && n < 3; ++n) {
        char tpath[PROC_PIDPATHINFO_MAXSIZE];
        strcpy(tpath, folderpath);
        strcat(tpath, lookup_paths[n]);
        lib_sciter_handle = dlopen(tpath, RTLD_LOCAL | RTLD_LAZY);
      }
    }
    if (!lib_sciter_handle) {
      fprintf(stderr, "[%s] Unable to load library: %s\n", __FILE__, dlerror());
      exit(EXIT_FAILURE);
    }

    SciterAPI_ptr sapi = (SciterAPI_ptr)dlsym(lib_sciter_handle, "SciterAPI");
    if (!sapi) {
      fprintf(stderr, "[%s] Unable to get symbol: %s\n", __FILE__, dlerror());
      exit(EXIT_FAILURE);
    }
    _api = sapi();
    // tiscript::ni( _api->TIScriptAPI() );
  }
  assert(_api);
  return _api;
}

#elif defined(ANDROID)

#if 1
EXTERN_C ISciterAPI *SciterAPI();

ISciterAPI *_SAPI(ISciterAPI *ext) {
  static ISciterAPI *_api = NULL;
  if (ext)
    _api = ext;
  else
    _api = SciterAPI();
  assert(_api);
  // if (!sapi) {
  //   fprintf(stderr, "[%s] Unable to get symbol: %s\n", __FILE__, dlerror());
  //   exit(EXIT_FAILURE);
  // }
  return _api;
}

#else
ISciterAPI *_SAPI(ISciterAPI *ext) {
  static ISciterAPI *_api = NULL;
  if (ext)
    _api = ext;
  if (!_api) {
    void *lib_sciter_handle = NULL;
    // 1. try to load from the same folder as this executable
    lib_sciter_handle = dlopen(SCITER_DLL_NAME, RTLD_LOCAL | RTLD_LAZY);
    if (!lib_sciter_handle) {
      fprintf(stderr, "[%s] Unable to load library: %s\n", dlerror(),
              SCITER_DLL_NAME);
    }

    SciterAPI_ptr sapi = (SciterAPI_ptr)dlsym(lib_sciter_handle, "SciterAPI");
    if (!sapi) {
      fprintf(stderr, "[%s] Unable to get symbol: %s\n", __FILE__, dlerror());
      exit(EXIT_FAILURE);
    }
    _api = sapi();
  }
  assert(_api);
  return _api;
}

#endif

#elif defined(LINUX)

#include <dlfcn.h>
#include <libgen.h>

// typedef ISciterAPI* SCAPI (*SciterAPI_ptr)();

ISciterAPI *_SAPI(ISciterAPI *ext) {
  static ISciterAPI *_api = NULL;
  if (ext)
    _api = ext;
  if (!_api) {

    char folderpath[2048] = {0};

    if (readlink("/proc/self/exe", folderpath, sizeof(folderpath)) != -1) {
      dirname(folderpath);
      // strcat  (pathbuf, "/");
    }

    void *lib_sciter_handle = NULL;

    {
      // 1. try to load from the same folder as this executable
      const char *lookup_paths[] = {"/" SCITER_DLL_NAME, NULL};
      for (int n = 0; !lib_sciter_handle; ++n) {
        if (!lookup_paths[n])
          break;
        char tpath[2048] = {0};
        strcpy(tpath, folderpath);
        strcat(tpath, lookup_paths[n]);
        // fprintf(stdout, "[%s]\n",tpath);
        lib_sciter_handle = dlopen(tpath, RTLD_LOCAL | RTLD_LAZY);
        if (!lib_sciter_handle) {
          fprintf(stderr, "[%s] Unable to load library: %s\n", dlerror(),
                  tpath);
        }
      }
    }

    if (!lib_sciter_handle) // 2. no luck, try to load from system paths
      lib_sciter_handle = dlopen(SCITER_DLL_NAME, RTLD_LOCAL | RTLD_LAZY);

    if (!lib_sciter_handle) {
      fprintf(stderr, "[%s] Unable to load library: %s\n", __FILE__, dlerror());
      exit(EXIT_FAILURE);
    }

    SciterAPI_ptr sapi = (SciterAPI_ptr)dlsym(lib_sciter_handle, "SciterAPI");
    if (!sapi) {
      fprintf(stderr, "[%s] Unable to get symbol: %s\n", __FILE__, dlerror());
      exit(EXIT_FAILURE);
    }
    _api = sapi();
  }
  assert(_api);
  return _api;
}

#endif

ISciterAPI *SAPI() { return _SAPI(NULL); }

LPSciterGraphicsAPI gapi() { return SAPI()->GetSciterGraphicsAPI(); }

LPSciterRequestAPI rapi() { return SAPI()->GetSciterRequestAPI(); }

// defining "official" API functions:

LPCWSTR SCAPI SciterClassName(void) { return SAPI()->SciterClassName(); }
UINT SCAPI SciterVersion(UINT n) { return SAPI()->SciterVersion(n); }
SBOOL SCAPI SciterDataReady(HWINDOW hwnd, LPCWSTR uri, LPCBYTE data,
                            UINT dataLength) {
  return SAPI()->SciterDataReady(hwnd, uri, data, dataLength);
}
SBOOL SCAPI SciterDataReadyAsync(HWINDOW hwnd, LPCWSTR uri, LPCBYTE data,
                                 UINT dataLength, LPVOID requestId) {
  return SAPI()->SciterDataReadyAsync(hwnd, uri, data, dataLength, requestId);
}
#if defined(WINDOWS) && !defined(WINDOWLESS)
LRESULT SCAPI SciterProc(HWINDOW hwnd, UINT msg, WPARAM wParam, LPARAM lParam) {
  return SAPI()->SciterProc(hwnd, msg, wParam, lParam);
}
LRESULT SCAPI SciterProcND(HWINDOW hwnd, UINT msg, WPARAM wParam, LPARAM lParam,
                           SBOOL *pbHandled) {
  return SAPI()->SciterProcND(hwnd, msg, wParam, lParam, pbHandled);
}
#endif
SBOOL SCAPI SciterLoadFile(HWINDOW hWndSciter, LPCWSTR filename) {
  return SAPI()->SciterLoadFile(hWndSciter, filename);
}
SBOOL SCAPI SciterLoadHtml(HWINDOW hWndSciter, LPCBYTE html, UINT htmlSize,
                           LPCWSTR baseUrl) {
  return SAPI()->SciterLoadHtml(hWndSciter, html, htmlSize, baseUrl);
}
VOID SCAPI SciterSetCallback(HWINDOW hWndSciter, LPSciterHostCallback cb,
                             LPVOID cbParam) {
  SAPI()->SciterSetCallback(hWndSciter, cb, cbParam);
}
SBOOL SCAPI SciterSetMasterCSS(LPCBYTE utf8, UINT numBytes) {
  return SAPI()->SciterSetMasterCSS(utf8, numBytes);
}
SBOOL SCAPI SciterAppendMasterCSS(LPCBYTE utf8, UINT numBytes) {
  return SAPI()->SciterAppendMasterCSS(utf8, numBytes);
}
SBOOL SCAPI SciterSetCSS(HWINDOW hWndSciter, LPCBYTE utf8, UINT numBytes,
                         LPCWSTR baseUrl, LPCWSTR mediaType) {
  return SAPI()->SciterSetCSS(hWndSciter, utf8, numBytes, baseUrl, mediaType);
}
SBOOL SCAPI SciterSetMediaType(HWINDOW hWndSciter, LPCWSTR mediaType) {
  return SAPI()->SciterSetMediaType(hWndSciter, mediaType);
}
SBOOL SCAPI SciterSetMediaVars(HWINDOW hWndSciter,
                               const SCITER_VALUE *mediaVars) {
  return SAPI()->SciterSetMediaVars(hWndSciter, mediaVars);
}
UINT SCAPI SciterGetMinWidth(HWINDOW hWndSciter) {
  return SAPI()->SciterGetMinWidth(hWndSciter);
}
UINT SCAPI SciterGetMinHeight(HWINDOW hWndSciter, UINT width) {
  return SAPI()->SciterGetMinHeight(hWndSciter, width);
}
SBOOL SCAPI SciterCall(HWINDOW hWnd, LPCSTR functionName, UINT argc,
                       const SCITER_VALUE *argv, SCITER_VALUE *retval) {
  return SAPI()->SciterCall(hWnd, functionName, argc, argv, retval);
}
SBOOL SCAPI SciterEval(HWINDOW hwnd, LPCWSTR script, UINT scriptLength,
                       SCITER_VALUE *pretval) {
  return SAPI()->SciterEval(hwnd, script, scriptLength, pretval);
}
VOID SCAPI SciterUpdateWindow(HWINDOW hwnd) {
  SAPI()->SciterUpdateWindow(hwnd);
}
SBOOL SCAPI SciterSetOption(HWINDOW hWnd, UINT option, UINT_PTR value) {
  return SAPI()->SciterSetOption(hWnd, option, value);
}
VOID SCAPI SciterGetPPI(HWINDOW hWndSciter, UINT *px, UINT *py) {
  SAPI()->SciterGetPPI(hWndSciter, px, py);
}
SBOOL SCAPI SciterGetViewExpando(HWINDOW hwnd, VALUE *pval) {
  return SAPI()->SciterGetViewExpando(hwnd, pval);
}
#if defined(WINDOWS) && !defined(WINDOWLESS)
SBOOL SCAPI SciterRenderD2D(HWINDOW hWndSciter,
                            IUnknown * /*ID2D1RenderTarget**/ prt) {
  return FALSE;
}
SBOOL SCAPI SciterD2DFactory(IUnknown ** /*ID2D1Factory ***/ ppf) {
  return FALSE;
}
SBOOL SCAPI SciterDWFactory(IUnknown ** /*IDWriteFactory ***/ ppf) {
  return FALSE;
}
#endif
SBOOL SCAPI SciterGraphicsCaps(LPUINT pcaps) {
  return SAPI()->SciterGraphicsCaps(pcaps);
}
SBOOL SCAPI SciterSetHomeURL(HWINDOW hWndSciter, LPCWSTR baseUrl) {
  return SAPI()->SciterSetHomeURL(hWndSciter, baseUrl);
}
#if defined(OSX) && !defined(WINDOWLESS)
HWINDOW SCAPI SciterCreateNSView(LPRECT frame) {
  return SAPI()->SciterCreateNSView(frame);
}
#endif
#if !defined(WINDOWLESS)
HWINDOW SCAPI SciterCreateWindow(UINT creationFlags, LPRECT frame, LPVOID,
                                 LPVOID, HWINDOW parent) {
  return SAPI()->SciterCreateWindow(creationFlags, frame, NULL, NULL, parent);
}
#endif

SCDOM_RESULT SCAPI Sciter_UseElement(HELEMENT he) {
  return SAPI()->Sciter_UseElement(he);
}
SCDOM_RESULT SCAPI Sciter_UnuseElement(HELEMENT he) {
  return SAPI()->Sciter_UnuseElement(he);
}
SCDOM_RESULT SCAPI SciterGetRootElement(HWINDOW hwnd, HELEMENT *phe) {
  return SAPI()->SciterGetRootElement(hwnd, phe);
}
SCDOM_RESULT SCAPI SciterGetFocusElement(HWINDOW hwnd, HELEMENT *phe) {
  return SAPI()->SciterGetFocusElement(hwnd, phe);
}
SCDOM_RESULT SCAPI SciterFindElement(HWINDOW hwnd, POINT pt, HELEMENT *phe) {
  return SAPI()->SciterFindElement(hwnd, pt, phe);
}
SCDOM_RESULT SCAPI SciterGetChildrenCount(HELEMENT he, UINT *count) {
  return SAPI()->SciterGetChildrenCount(he, count);
}
SCDOM_RESULT SCAPI SciterGetNthChild(HELEMENT he, UINT n, HELEMENT *phe) {
  return SAPI()->SciterGetNthChild(he, n, phe);
}
SCDOM_RESULT SCAPI SciterGetParentElement(HELEMENT he, HELEMENT *p_parent_he) {
  return SAPI()->SciterGetParentElement(he, p_parent_he);
}
SCDOM_RESULT SCAPI SciterGetElementHtmlCB(HELEMENT he, SBOOL outer,
                                          LPCBYTE_RECEIVER *rcv,
                                          LPVOID rcv_param) {
  return SAPI()->SciterGetElementHtmlCB(he, outer, rcv, rcv_param);
}
SCDOM_RESULT SCAPI SciterGetElementTextCB(HELEMENT he, LPCWSTR_RECEIVER *rcv,
                                          LPVOID rcv_param) {
  return SAPI()->SciterGetElementTextCB(he, rcv, rcv_param);
}
SCDOM_RESULT SCAPI SciterSetElementText(HELEMENT he, LPCWSTR utf16,
                                        UINT length) {
  return SAPI()->SciterSetElementText(he, utf16, length);
}
SCDOM_RESULT SCAPI SciterGetAttributeCount(HELEMENT he, LPUINT p_count) {
  return SAPI()->SciterGetAttributeCount(he, p_count);
}
SCDOM_RESULT SCAPI SciterGetNthAttributeNameCB(HELEMENT he, UINT n,
                                               LPCSTR_RECEIVER *rcv,
                                               LPVOID rcv_param) {
  return SAPI()->SciterGetNthAttributeNameCB(he, n, rcv, rcv_param);
}
SCDOM_RESULT SCAPI SciterGetNthAttributeValueCB(HELEMENT he, UINT n,
                                                LPCWSTR_RECEIVER *rcv,
                                                LPVOID rcv_param) {
  return SAPI()->SciterGetNthAttributeValueCB(he, n, rcv, rcv_param);
}
SCDOM_RESULT SCAPI SciterGetAttributeByNameCB(HELEMENT he, LPCSTR name,
                                              LPCWSTR_RECEIVER *rcv,
                                              LPVOID rcv_param) {
  return SAPI()->SciterGetAttributeByNameCB(he, name, rcv, rcv_param);
}
SCDOM_RESULT SCAPI SciterSetAttributeByName(HELEMENT he, LPCSTR name,
                                            LPCWSTR value) {
  return SAPI()->SciterSetAttributeByName(he, name, value);
}
SCDOM_RESULT SCAPI SciterClearAttributes(HELEMENT he) {
  return SAPI()->SciterClearAttributes(he);
}
SCDOM_RESULT SCAPI SciterGetElementIndex(HELEMENT he, LPUINT p_index) {
  return SAPI()->SciterGetElementIndex(he, p_index);
}
SCDOM_RESULT SCAPI SciterGetElementType(HELEMENT he, LPCSTR *p_type) {
  return SAPI()->SciterGetElementType(he, p_type);
}
SCDOM_RESULT SCAPI SciterGetElementTypeCB(HELEMENT he, LPCSTR_RECEIVER *rcv,
                                          LPVOID rcv_param) {
  return SAPI()->SciterGetElementTypeCB(he, rcv, rcv_param);
}
SCDOM_RESULT SCAPI SciterGetStyleAttributeCB(HELEMENT he, LPCSTR name,
                                             LPCWSTR_RECEIVER *rcv,
                                             LPVOID rcv_param) {
  return SAPI()->SciterGetStyleAttributeCB(he, name, rcv, rcv_param);
}
SCDOM_RESULT SCAPI SciterSetStyleAttribute(HELEMENT he, LPCSTR name,
                                           LPCWSTR value) {
  return SAPI()->SciterSetStyleAttribute(he, name, value);
}
SCDOM_RESULT SCAPI SciterGetElementLocation(HELEMENT he, LPRECT p_location,
                                            UINT areas /*ELEMENT_AREAS*/) {
  return SAPI()->SciterGetElementLocation(he, p_location, areas);
}
SCDOM_RESULT SCAPI SciterScrollToView(HELEMENT he, UINT SciterScrollFlags) {
  return SAPI()->SciterScrollToView(he, SciterScrollFlags);
}
SCDOM_RESULT SCAPI SciterUpdateElement(HELEMENT he, SBOOL andForceRender) {
  return SAPI()->SciterUpdateElement(he, andForceRender);
}
SCDOM_RESULT SCAPI SciterRefreshElementArea(HELEMENT he, RECT rc) {
  return SAPI()->SciterRefreshElementArea(he, rc);
}
SCDOM_RESULT SCAPI SciterSetCapture(HELEMENT he) {
  return SAPI()->SciterSetCapture(he);
}
SCDOM_RESULT SCAPI SciterReleaseCapture(HELEMENT he) {
  return SAPI()->SciterReleaseCapture(he);
}
SCDOM_RESULT SCAPI SciterGetElementHwnd(HELEMENT he, HWINDOW *p_hwnd,
                                        SBOOL rootWindow) {
  return SAPI()->SciterGetElementHwnd(he, p_hwnd, rootWindow);
}
SCDOM_RESULT SCAPI SciterCombineURL(HELEMENT he, LPWSTR szUrlBuffer,
                                    UINT UrlBufferSize) {
  return SAPI()->SciterCombineURL(he, szUrlBuffer, UrlBufferSize);
}
SCDOM_RESULT SCAPI SciterSelectElements(HELEMENT he, LPCSTR CSS_selectors,
                                        SciterElementCallback *callback,
                                        LPVOID param) {
  return SAPI()->SciterSelectElements(he, CSS_selectors, callback, param);
}
SCDOM_RESULT SCAPI SciterSelectElementsW(HELEMENT he, LPCWSTR CSS_selectors,
                                         SciterElementCallback *callback,
                                         LPVOID param) {
  return SAPI()->SciterSelectElementsW(he, CSS_selectors, callback, param);
}
SCDOM_RESULT SCAPI SciterSelectParent(HELEMENT he, LPCSTR selector, UINT depth,
                                      HELEMENT *heFound) {
  return SAPI()->SciterSelectParent(he, selector, depth, heFound);
}
SCDOM_RESULT SCAPI SciterSelectParentW(HELEMENT he, LPCWSTR selector,
                                       UINT depth, HELEMENT *heFound) {
  return SAPI()->SciterSelectParentW(he, selector, depth, heFound);
}
SCDOM_RESULT SCAPI SciterSetElementHtml(HELEMENT he, const BYTE *html,
                                        UINT htmlLength, UINT where) {
  return SAPI()->SciterSetElementHtml(he, html, htmlLength, where);
}
SCDOM_RESULT SCAPI SciterGetElementUID(HELEMENT he, UINT *puid) {
  return SAPI()->SciterGetElementUID(he, puid);
}
SCDOM_RESULT SCAPI SciterGetElementByUID(HWINDOW hwnd, UINT uid,
                                         HELEMENT *phe) {
  return SAPI()->SciterGetElementByUID(hwnd, uid, phe);
}
SCDOM_RESULT SCAPI SciterShowPopup(HELEMENT hePopup, HELEMENT heAnchor,
                                   UINT placement) {
  return SAPI()->SciterShowPopup(hePopup, heAnchor, placement);
}
SCDOM_RESULT SCAPI SciterShowPopupAt(HELEMENT hePopup, POINT pos,
                                     UINT placement) {
  return SAPI()->SciterShowPopupAt(hePopup, pos, placement);
}
SCDOM_RESULT SCAPI SciterHidePopup(HELEMENT he) {
  return SAPI()->SciterHidePopup(he);
}
SCDOM_RESULT SCAPI SciterGetElementState(HELEMENT he, UINT *pstateBits) {
  return SAPI()->SciterGetElementState(he, pstateBits);
}
SCDOM_RESULT SCAPI SciterSetElementState(HELEMENT he, UINT stateBitsToSet,
                                         UINT stateBitsToClear,
                                         SBOOL updateView) {
  return SAPI()->SciterSetElementState(he, stateBitsToSet, stateBitsToClear,
                                       updateView);
}
SCDOM_RESULT SCAPI SciterCreateElement(LPCSTR tagname, LPCWSTR textOrNull,
                                       /*out*/ HELEMENT *phe) {
  return SAPI()->SciterCreateElement(tagname, textOrNull, phe);
}
SCDOM_RESULT SCAPI SciterCloneElement(HELEMENT he, /*out*/ HELEMENT *phe) {
  return SAPI()->SciterCloneElement(he, phe);
}
SCDOM_RESULT SCAPI SciterInsertElement(HELEMENT he, HELEMENT hparent,
                                       UINT index) {
  return SAPI()->SciterInsertElement(he, hparent, index);
}
SCDOM_RESULT SCAPI SciterDetachElement(HELEMENT he) {
  return SAPI()->SciterDetachElement(he);
}
SCDOM_RESULT SCAPI SciterDeleteElement(HELEMENT he) {
  return SAPI()->SciterDeleteElement(he);
}
SCDOM_RESULT SCAPI SciterSetTimer(HELEMENT he, UINT milliseconds,
                                  UINT_PTR timer_id) {
  return SAPI()->SciterSetTimer(he, milliseconds, timer_id);
}
SCDOM_RESULT SCAPI SciterDetachEventHandler(HELEMENT he,
                                            LPELEMENT_EVENT_PROC pep,
                                            LPVOID tag) {
  return SAPI()->SciterDetachEventHandler(he, pep, tag);
}
SCDOM_RESULT SCAPI SciterAttachEventHandler(HELEMENT he,
                                            LPELEMENT_EVENT_PROC pep,
                                            LPVOID tag) {
  return SAPI()->SciterAttachEventHandler(he, pep, tag);
}
SCDOM_RESULT SCAPI SciterWindowAttachEventHandler(HWINDOW hwndLayout,
                                                  LPELEMENT_EVENT_PROC pep,
                                                  LPVOID tag,
                                                  UINT subscription) {
  return SAPI()->SciterWindowAttachEventHandler(hwndLayout, pep, tag,
                                                subscription);
}
SCDOM_RESULT SCAPI SciterWindowDetachEventHandler(HWINDOW hwndLayout,
                                                  LPELEMENT_EVENT_PROC pep,
                                                  LPVOID tag) {
  return SAPI()->SciterWindowDetachEventHandler(hwndLayout, pep, tag);
}
SCDOM_RESULT SCAPI SciterSendEvent(HELEMENT he, UINT appEventCode,
                                   HELEMENT heSource, UINT_PTR reason,
                                   /*out*/ SBOOL *handled) {
  return SAPI()->SciterSendEvent(he, appEventCode, heSource, reason, handled);
}
SCDOM_RESULT SCAPI SciterPostEvent(HELEMENT he, UINT appEventCode,
                                   HELEMENT heSource, UINT_PTR reason) {
  return SAPI()->SciterPostEvent(he, appEventCode, heSource, reason);
}
SCDOM_RESULT SCAPI SciterFireEvent(const BEHAVIOR_EVENT_PARAMS *evt, SBOOL post,
                                   SBOOL *handled) {
  return SAPI()->SciterFireEvent(evt, post, handled);
}
SCDOM_RESULT SCAPI SciterCallBehaviorMethod(HELEMENT he,
                                            struct METHOD_PARAMS *params) {
  return SAPI()->SciterCallBehaviorMethod(he, params);
}
SCDOM_RESULT SCAPI SciterRequestElementData(HELEMENT he, LPCWSTR url,
                                            UINT dataType, HELEMENT initiator) {
  return SAPI()->SciterRequestElementData(he, url, dataType, initiator);
}
SCDOM_RESULT SCAPI SciterHttpRequest(HELEMENT he, LPCWSTR url, UINT dataType,
                                     UINT requestType,
                                     struct REQUEST_PARAM *requestParams,
                                     UINT nParams) {
  return SAPI()->SciterHttpRequest(he, url, dataType, requestType,
                                   requestParams, nParams);
}
SCDOM_RESULT SCAPI SciterGetScrollInfo(HELEMENT he, LPPOINT scrollPos,
                                       LPRECT viewRect, LPSIZE contentSize) {
  return SAPI()->SciterGetScrollInfo(he, scrollPos, viewRect, contentSize);
}
SCDOM_RESULT SCAPI SciterSetScrollPos(HELEMENT he, POINT scrollPos,
                                      SBOOL smooth) {
  return SAPI()->SciterSetScrollPos(he, scrollPos, smooth);
}
SCDOM_RESULT SCAPI SciterGetElementIntrinsicWidths(HELEMENT he, INT *pMinWidth,
                                                   INT *pMaxWidth) {
  return SAPI()->SciterGetElementIntrinsicWidths(he, pMinWidth, pMaxWidth);
}
SCDOM_RESULT SCAPI SciterGetElementIntrinsicHeight(HELEMENT he, INT forWidth,
                                                   INT *pHeight) {
  return SAPI()->SciterGetElementIntrinsicHeight(he, forWidth, pHeight);
}
SCDOM_RESULT SCAPI SciterIsElementVisible(HELEMENT he, SBOOL *pVisible) {
  return SAPI()->SciterIsElementVisible(he, pVisible);
}
SCDOM_RESULT SCAPI SciterIsElementEnabled(HELEMENT he, SBOOL *pEnabled) {
  return SAPI()->SciterIsElementEnabled(he, pEnabled);
}
SCDOM_RESULT SCAPI SciterSortElements(HELEMENT he, UINT firstIndex,
                                      UINT lastIndex,
                                      ELEMENT_COMPARATOR *cmpFunc,
                                      LPVOID cmpFuncParam) {
  return SAPI()->SciterSortElements(he, firstIndex, lastIndex, cmpFunc,
                                    cmpFuncParam);
}
SCDOM_RESULT SCAPI SciterSwapElements(HELEMENT he1, HELEMENT he2) {
  return SAPI()->SciterSwapElements(he1, he2);
}
SCDOM_RESULT SCAPI SciterTraverseUIEvent(UINT evt, LPVOID eventCtlStruct,
                                         SBOOL *bOutProcessed) {
  return SAPI()->SciterTraverseUIEvent(evt, eventCtlStruct, bOutProcessed);
}
SCDOM_RESULT SCAPI SciterCallScriptingMethod(HELEMENT he, LPCSTR name,
                                             const VALUE *argv, UINT argc,
                                             VALUE *retval) {
  return SAPI()->SciterCallScriptingMethod(he, name, argv, argc, retval);
}
SCDOM_RESULT SCAPI SciterCallScriptingFunction(HELEMENT he, LPCSTR name,
                                               const VALUE *argv, UINT argc,
                                               VALUE *retval) {
  return SAPI()->SciterCallScriptingFunction(he, name, argv, argc, retval);
}
SCDOM_RESULT SCAPI SciterEvalElementScript(HELEMENT he, LPCWSTR script,
                                           UINT scriptLength, VALUE *retval) {
  return SAPI()->SciterEvalElementScript(he, script, scriptLength, retval);
}
SCDOM_RESULT SCAPI SciterAttachHwndToElement(HELEMENT he, HWINDOW hwnd) {
  return SAPI()->SciterAttachHwndToElement(he, hwnd);
}
SCDOM_RESULT SCAPI SciterControlGetType(HELEMENT he, /*CTL_TYPE*/ UINT *pType) {
  return SAPI()->SciterControlGetType(he, pType);
}
SCDOM_RESULT SCAPI SciterGetValue(HELEMENT he, VALUE *pval) {
  return SAPI()->SciterGetValue(he, pval);
}
SCDOM_RESULT SCAPI SciterSetValue(HELEMENT he, const VALUE *pval) {
  return SAPI()->SciterSetValue(he, pval);
}
SCDOM_RESULT SCAPI SciterGetExpando(HELEMENT he, VALUE *pval,
                                    SBOOL forceCreation) {
  return SAPI()->SciterGetExpando(he, pval, forceCreation);
}
// SCDOM_RESULT SCAPI SciterGetObject( HELEMENT he, void* pval, SBOOL
// forceCreation ) { return SAPI()->SciterGetObject( he, pval, forceCreation );
// } SCDOM_RESULT SCAPI SciterGetElementNamespace(  HELEMENT he, void* pval) {
// return SAPI()->SciterGetElementNamespace( he,pval); }
SCDOM_RESULT SCAPI SciterGetHighlightedElement(HWINDOW hwnd, HELEMENT *phe) {
  return SAPI()->SciterGetHighlightedElement(hwnd, phe);
}
SCDOM_RESULT SCAPI SciterSetHighlightedElement(HWINDOW hwnd, HELEMENT he) {
  return SAPI()->SciterSetHighlightedElement(hwnd, he);
}
SCDOM_RESULT SCAPI SciterNodeAddRef(HNODE hn) {
  return SAPI()->SciterNodeAddRef(hn);
}
SCDOM_RESULT SCAPI SciterNodeRelease(HNODE hn) {
  return SAPI()->SciterNodeRelease(hn);
}
SCDOM_RESULT SCAPI SciterNodeCastFromElement(HELEMENT he, HNODE *phn) {
  return SAPI()->SciterNodeCastFromElement(he, phn);
}
SCDOM_RESULT SCAPI SciterNodeCastToElement(HNODE hn, HELEMENT *he) {
  return SAPI()->SciterNodeCastToElement(hn, he);
}
SCDOM_RESULT SCAPI SciterNodeFirstChild(HNODE hn, HNODE *phn) {
  return SAPI()->SciterNodeFirstChild(hn, phn);
}
SCDOM_RESULT SCAPI SciterNodeLastChild(HNODE hn, HNODE *phn) {
  return SAPI()->SciterNodeLastChild(hn, phn);
}
SCDOM_RESULT SCAPI SciterNodeNextSibling(HNODE hn, HNODE *phn) {
  return SAPI()->SciterNodeNextSibling(hn, phn);
}
SCDOM_RESULT SCAPI SciterNodePrevSibling(HNODE hn, HNODE *phn) {
  return SAPI()->SciterNodePrevSibling(hn, phn);
}
SCDOM_RESULT SCAPI SciterNodeParent(HNODE hnode, HELEMENT *pheParent) {
  return SAPI()->SciterNodeParent(hnode, pheParent);
}
SCDOM_RESULT SCAPI SciterNodeNthChild(HNODE hnode, UINT n, HNODE *phn) {
  return SAPI()->SciterNodeNthChild(hnode, n, phn);
}
SCDOM_RESULT SCAPI SciterNodeChildrenCount(HNODE hnode, UINT *pn) {
  return SAPI()->SciterNodeChildrenCount(hnode, pn);
}
SCDOM_RESULT SCAPI SciterNodeType(HNODE hnode, UINT *pNodeType /*NODE_TYPE*/) {
  return SAPI()->SciterNodeType(hnode, pNodeType);
}
SCDOM_RESULT SCAPI SciterNodeGetText(HNODE hnode, LPCWSTR_RECEIVER *rcv,
                                     LPVOID rcv_param) {
  return SAPI()->SciterNodeGetText(hnode, rcv, rcv_param);
}
SCDOM_RESULT SCAPI SciterNodeSetText(HNODE hnode, LPCWSTR text,
                                     UINT textLength) {
  return SAPI()->SciterNodeSetText(hnode, text, textLength);
}
SCDOM_RESULT SCAPI SciterNodeInsert(HNODE hnode, UINT where /*NODE_INS_TARGET*/,
                                    HNODE what) {
  return SAPI()->SciterNodeInsert(hnode, where, what);
}
SCDOM_RESULT SCAPI SciterNodeRemove(HNODE hnode, SBOOL finalize) {
  return SAPI()->SciterNodeRemove(hnode, finalize);
}
SCDOM_RESULT SCAPI SciterCreateTextNode(LPCWSTR text, UINT textLength,
                                        HNODE *phnode) {
  return SAPI()->SciterCreateTextNode(text, textLength, phnode);
}
SCDOM_RESULT SCAPI SciterCreateCommentNode(LPCWSTR text, UINT textLength,
                                           HNODE *phnode) {
  return SAPI()->SciterCreateCommentNode(text, textLength, phnode);
}

// HVM   SCAPI SciterGetVM( HWINDOW hwnd )  { return SAPI()->SciterGetVM(hwnd);
// }

UINT SCAPI ValueInit(VALUE *pval) { return SAPI()->ValueInit(pval); }
UINT SCAPI ValueClear(VALUE *pval) { return SAPI()->ValueClear(pval); }
UINT SCAPI ValueCompare(const VALUE *pval1, const VALUE *pval2) {
  return SAPI()->ValueCompare(pval1, pval2);
}
UINT SCAPI ValueCopy(VALUE *pdst, const VALUE *psrc) {
  return SAPI()->ValueCopy(pdst, psrc);
}
UINT SCAPI ValueIsolate(VALUE *pdst) { return SAPI()->ValueIsolate(pdst); }
UINT SCAPI ValueType(const VALUE *pval, UINT *pType, UINT *pUnits) {
  return SAPI()->ValueType(pval, pType, pUnits);
}
UINT SCAPI ValueStringData(const VALUE *pval, LPCWSTR *pChars,
                           UINT *pNumChars) {
  return SAPI()->ValueStringData(pval, pChars, pNumChars);
}
UINT SCAPI ValueStringDataSet(VALUE *pval, LPCWSTR chars, UINT numChars,
                              UINT units) {
  return SAPI()->ValueStringDataSet(pval, chars, numChars, units);
}
UINT SCAPI ValueIntData(const VALUE *pval, INT *pData) {
  return SAPI()->ValueIntData(pval, pData);
}
UINT SCAPI ValueIntDataSet(VALUE *pval, INT data, UINT type, UINT units) {
  return SAPI()->ValueIntDataSet(pval, data, type, units);
}
UINT SCAPI ValueInt64Data(const VALUE *pval, INT64 *pData) {
  return SAPI()->ValueInt64Data(pval, pData);
}
UINT SCAPI ValueInt64DataSet(VALUE *pval, INT64 data, UINT type, UINT units) {
  return SAPI()->ValueInt64DataSet(pval, data, type, units);
}
UINT SCAPI ValueFloatData(const VALUE *pval, FLOAT_VALUE *pData) {
  return SAPI()->ValueFloatData(pval, pData);
}
UINT SCAPI ValueFloatDataSet(VALUE *pval, FLOAT_VALUE data, UINT type,
                             UINT units) {
  return SAPI()->ValueFloatDataSet(pval, data, type, units);
}
UINT SCAPI ValueBinaryData(const VALUE *pval, LPCBYTE *pBytes, UINT *pnBytes) {
  return SAPI()->ValueBinaryData(pval, pBytes, pnBytes);
}
UINT SCAPI ValueBinaryDataSet(VALUE *pval, LPCBYTE pBytes, UINT nBytes,
                              UINT type, UINT units) {
  return SAPI()->ValueBinaryDataSet(pval, pBytes, nBytes, type, units);
}
UINT SCAPI ValueElementsCount(const VALUE *pval, INT *pn) {
  return SAPI()->ValueElementsCount(pval, pn);
}
UINT SCAPI ValueNthElementValue(const VALUE *pval, INT n, VALUE *pretval) {
  return SAPI()->ValueNthElementValue(pval, n, pretval);
}
UINT SCAPI ValueNthElementValueSet(VALUE *pval, INT n,
                                   const VALUE *pval_to_set) {
  return SAPI()->ValueNthElementValueSet(pval, n, pval_to_set);
}
UINT SCAPI ValueNthElementKey(const VALUE *pval, INT n, VALUE *pretval) {
  return SAPI()->ValueNthElementKey(pval, n, pretval);
}
UINT SCAPI ValueEnumElements(const VALUE *pval, KeyValueCallback *penum,
                             LPVOID param) {
  return SAPI()->ValueEnumElements(pval, penum, param);
}
UINT SCAPI ValueSetValueToKey(VALUE *pval, const VALUE *pkey,
                              const VALUE *pval_to_set) {
  return SAPI()->ValueSetValueToKey(pval, pkey, pval_to_set);
}
UINT SCAPI ValueGetValueOfKey(const VALUE *pval, const VALUE *pkey,
                              VALUE *pretval) {
  return SAPI()->ValueGetValueOfKey(pval, pkey, pretval);
}
UINT SCAPI ValueToString(VALUE *pval, UINT how) {
  return SAPI()->ValueToString(pval, how);
}
UINT SCAPI ValueFromString(VALUE *pval, LPCWSTR str, UINT strLength, UINT how) {
  return SAPI()->ValueFromString(pval, str, strLength, how);
}
UINT SCAPI ValueInvoke(const VALUE *pval, VALUE *pthis, UINT argc,
                       const VALUE *argv, VALUE *pretval, LPCWSTR url) {
  return SAPI()->ValueInvoke(pval, pthis, argc, argv, pretval, url);
}
UINT SCAPI ValueNativeFunctorSet(VALUE *pval, NATIVE_FUNCTOR_INVOKE *pinvoke,
                                 NATIVE_FUNCTOR_RELEASE *prelease, VOID *tag) {
  return SAPI()->ValueNativeFunctorSet(pval, pinvoke, prelease, tag);
}
SBOOL SCAPI ValueIsNativeFunctor(const VALUE *pval) {
  return SAPI()->ValueIsNativeFunctor(pval);
}

HSARCHIVE SCAPI SciterOpenArchive(LPCBYTE archiveData, UINT archiveDataLength) {
  return SAPI()->SciterOpenArchive(archiveData, archiveDataLength);
}
SBOOL SCAPI SciterGetArchiveItem(HSARCHIVE harc, LPCWSTR path, LPCBYTE *pdata,
                                 UINT *pdataLength) {
  return SAPI()->SciterGetArchiveItem(harc, path, pdata, pdataLength);
}
SBOOL SCAPI SciterCloseArchive(HSARCHIVE harc) {
  return SAPI()->SciterCloseArchive(harc);
}

#if defined(WINDOWS) && !defined(WINDOWLESS)
SBOOL SCAPI SciterCreateOnDirectXWindow(HWINDOW hwnd, IUnknown *pSwapChain) {
  return FALSE;
}
SBOOL SCAPI SciterRenderOnDirectXWindow(HWINDOW hwnd,
                                        HELEMENT elementToRenderOrNull,
                                        SBOOL frontLayer) {
  return FALSE;
}
SBOOL SCAPI SciterRenderOnDirectXTexture(HWINDOW hwnd,
                                         HELEMENT elementToRenderOrNull,
                                         IUnknown *surface) {
  return FALSE;
}
#endif

SBOOL SCAPI SciterProcX(HWINDOW hwnd, SCITER_X_MSG *pMsg) {
  return SAPI()->SciterProcX(hwnd, pMsg);
}
#ifdef __cplusplus
template<class MSG> SBOOL SCAPI SciterProcX(HWINDOW hwnd, const MSG &msg) {
  static_assert(offsetof(MSG, header) == 0,
                "must contain SCITER_X_MSG as first memeber");
  static_assert(std::is_same<decltype(MSG::header), SCITER_X_MSG>::value,
                "must contain SCITER_X_MSG");
  return SAPI()->SciterProcX(hwnd, (SCITER_X_MSG *)(&msg));
}
#endif

UINT64 SCAPI SciterAtomValue(const char *name) {
  return SAPI()->SciterAtomValue(name);
}
UINT64 SCAPI SciterAtomNameCB(UINT64 atomv, LPCSTR_RECEIVER *rcv,
                              LPVOID rcv_param) {
  return SAPI()->SciterAtomNameCB(atomv, rcv, rcv_param);
}
SBOOL SCAPI SciterSetGlobalAsset(som_asset_t *pass) {
  return SAPI()->SciterSetGlobalAsset(pass);
}

UINT SCAPI SciterElementUnwrap(const VALUE *pval, HELEMENT *ppElement) {
  return SAPI()->SciterElementUnwrap(pval, ppElement);
}
UINT SCAPI SciterElementWrap(VALUE *pval, HELEMENT pElement) {
  return SAPI()->SciterElementWrap(pval, pElement);
}

UINT SCAPI SciterNodeUnwrap(const VALUE *pval, HNODE *ppNode) {
  return SAPI()->SciterNodeUnwrap(pval, ppNode);
}
UINT SCAPI SciterNodeWrap(VALUE *pval, HNODE pNode) {
  return SAPI()->SciterNodeWrap(pval, pNode);
}

SBOOL SCAPI SciterReleaseGlobalAsset(som_asset_t *pass) {
  return SAPI()->SciterReleaseGlobalAsset(pass);
}

INT_PTR SCAPI SciterExec(UINT appCmd, UINT_PTR p1, UINT_PTR p2) {
  return SAPI()->SciterExec(appCmd, p1, p2);
}

INT_PTR SCAPI SciterWindowExec(HWINDOW hwnd, UINT windowCmd, UINT_PTR p1,
                               UINT_PTR p2) {
  return SAPI()->SciterWindowExec(hwnd, windowCmd, p1, p2);
}
